In [102]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [103]:
calls = pd.read_excel(r"C:\Users\Jenifer\OneDrive\Desktop\call center performance analysis\Datasets\call_center (1).xlsx",header=2,usecols="B:H")

In [104]:
calls.head()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,Call_7271,C0003,116.0,R05,2023-01-01,128.0,4.9
1,Call_7272,C0004,NaN,R05,2023-01-01,135.0,2.9
2,Call_7273,C0005,68.0,R02,2023-01-01,NaN,4.7
3,Call_7274,C0014,119.0,R02,2023-01-01,22.0,2.9
4,Call_7275,C0011,128.0,R01,2023-01-02,31.0,NaN

In [105]:
customers = pd.read_excel(r"C:\Users\Jenifer\OneDrive\Desktop\call center performance analysis\Datasets\call_center (1).xlsx",header=2,usecols="L:O",nrows=15)

In [106]:
customers

   Customer ID.1  Gedner  Age        City
0          C0001    Male   41    Columbus
1          C0002    Male   31   Cleveland
2          C0003    Male   26  Cincinnati
3          C0004    Male   36  Cincinnati
4          C0005    Male   37    Columbus
5          C0006    Male   23    Columbus
6          C0007  Female   22   Cleveland
7          C0008  Female   42   Cleveland
8          C0009  Female   25    Columbus
9          C0010  Female   30   Cleveland
10         C0011  Female   30  Cincinnati
11         C0012  Female   28  Cincinnati
12         C0013  Female   37   Cleveland
13         C0014  Female   38    Columbus
14         C0015  Female   43   Cleveland

In [107]:
type(calls)
type(customers)

pandas.core.frame.DataFrame

In [108]:
calls.shape

(1000, 7)

In [109]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'Purchase Amount', 'Satisfaction Rating'],
      dtype='object')

In [110]:
calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   object
 1   Customer ID          1000 non-null   object
 2   Duration             997 non-null    float64
 3   Representative       997 non-null    object
 4   Date of Call         1000 non-null   datetime64[ns]
 5   Purchase Amount      997 non-null    float64
 6   Satisfaction Rating  996 non-null    float64
dtypes: datetime64[ns](1), float64(3), object(3)
memory usage: 54.8+ KB

In [111]:
calls.describe()

,Duration,Date of Call,Purchase Amount,Satisfaction Rating
count,997.000000,1000,997.00000,996.000000
mean,89.814443,2023-06-15 00:34:33.600000,96.76329,3.886044
min,2.000000,2023-01-01 00:00:00,20.00000,0.000000
25%,62.000000,2023-03-20 00:00:00,50.00000,3.400000
50%,89.000000,2023-05-25 12:00:00,88.00000,4.000000
75%,119.000000,2023-09-24 00:00:00,130.00000,4.500000
max,176.000000,2023-12-31 00:00:00,225.00000,5.000000
std,37.669599,NaN,52.47235,0.835131

In [112]:
calls.isnull().sum()

Call number            0
Customer ID            0
Duration               3
Representative         3
Date of Call           0
Purchase Amount        3
Satisfaction Rating    4
dtype: int64

In [113]:
customers.isnull().sum()

Customer ID.1    0
Gedner           0
Age              0
City             0
dtype: int64

In [114]:
calls[calls.isnull().any(axis=1)]

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
1,Call_7272,C0004,NaN,R05,2023-01-01,135.0,2.9
2,Call_7273,C0005,68.0,R02,2023-01-01,NaN,4.7
4,Call_7275,C0011,128.0,R01,2023-01-02,31.0,NaN
6,Call_7277,C0007,NaN,R05,2023-01-03,NaN,4.7
8,Call_7279,C0005,31.0,NaN,2023-01-03,135.0,3.6
9,Call_7280,C0010,44.0,R03,2023-01-03,105.0,NaN
10,Call_7281,C0011,NaN,R02,2023-01-03,69.0,4.9
15,Call_7286,C0010,176.0,NaN,2023-01-05,NaN,4.8
20,Call_7291,C0004,128.0,R05,2023-01-06,72.0,NaN
22,Call_7293,C0003,67.0,NaN,2023-01-08,165.0,4.5
30,Call_7301,C0009,80.0,R05,2023-01-10,140.0,NaN

In [115]:
calls.isnull().any()

Call number            False
Customer ID            False
Duration                True
Representative          True
Date of Call           False
Purchase Amount         True
Satisfaction Rating     True
dtype: bool

In [116]:
calls.isnull().all()

Call number            False
Customer ID            False
Duration               False
Representative         False
Date of Call           False
Purchase Amount        False
Satisfaction Rating    False
dtype: bool

In [117]:
calls['Purchase Amount'].fillna(calls['Purchase Amount'].mean(),inplace=True)

C:\Users\Jenifer\AppData\Local\Temp\ipykernel_18328\4007421738.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  calls['Purchase Amount'].fillna(calls['Purchase Amount'].mean(),inplace=True)

In [118]:
calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   object
 1   Customer ID          1000 non-null   object
 2   Duration             997 non-null    float64
 3   Representative       997 non-null    object
 4   Date of Call         1000 non-null   datetime64[ns]
 5   Purchase Amount      1000 non-null   float64
 6   Satisfaction Rating  996 non-null    float64
dtypes: datetime64[ns](1), float64(3), object(3)
memory usage: 54.8+ KB

In [119]:
calls.duplicated().sum()

np.int64(0)

In [120]:
calls.drop_duplicates().all()

C:\Users\Jenifer\AppData\Local\Temp\ipykernel_18328\2427564813.py:1: FutureWarning: 'all' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).all() instead.
  calls.drop_duplicates().all()

Call number             True
Customer ID             True
Duration                True
Representative          True
Date of Call            True
Purchase Amount         True
Satisfaction Rating    False
dtype: bool

In [121]:
calls.drop_duplicates().all(axis=1).sum()

C:\Users\Jenifer\AppData\Local\Temp\ipykernel_18328\2433151174.py:1: FutureWarning: 'all' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).all() instead.
  calls.drop_duplicates().all(axis=1).sum()

np.int64(999)

In [122]:
calls.drop_duplicates(inplace=True)

In [123]:
calls['Date of Call']=pd.to_datetime(calls['Date of Call'])

In [124]:
calls.dtypes

Call number                    object
Customer ID                    object
Duration                      float64
Representative                 object
Date of Call           datetime64[ns]
Purchase Amount               float64
Satisfaction Rating           float64
dtype: object

In [125]:
calls.rename(columns={'Purchase Amount':'Amount','Satisfaction Rating':'Rating'},inplace=True)

In [127]:
calls[['Amount','Representative','Duration','Rating']]

        Amount Representative  Duration  Rating
0    128.00000            R05     116.0     4.9
1    135.00000            R05       NaN     2.9
2     96.76329            R02      68.0     4.7
3     22.00000            R02     119.0     2.9
4     31.00000            R01     128.0     NaN
..         ...            ...       ...     ...
995   28.00000            R05      81.0     3.9
996  215.00000            R04     127.0     3.8
997  115.00000            R05     146.0     2.3
998   64.00000            R05     123.0     3.7
999   40.00000            R01     114.0     3.9

[1000 rows x 4 columns]

In [128]:
type(calls['Customer ID'])

pandas.core.series.Series

In [129]:
calls.Rating.sort_values(ascending=False)

96     5.0
577    5.0
921    5.0
605    5.0
104    5.0
      ...
69     0.0
4      NaN
9      NaN
20     NaN
30     NaN
Name: Rating, Length: 1000, dtype: float64

In [130]:
calls.Representative.unique()

array(['R05', 'R02', 'R01', 'R04', nan, 'R03'], dtype=object)

In [131]:
customers.City.unique()

array(['Columbus', 'Cleveland', 'Cincinnati'], dtype=object)

In [134]:
repcount=calls.Representative.value_counts()
repcount.max()

217

In [136]:
rep_count=calls.groupby("Representative")['Rating'].mean()
print(rep_count)

Representative
R01    3.928723
R02    3.871889
R03    3.863592
R04    3.894054
R05    3.870558
Name: Rating, dtype: float64

In [139]:
High_call=calls.groupby("Representative")["Call number"].count()
High_call.max()

217

In [142]:
merge_table=pd.merge(calls,customers,left_on="Customer ID",right_on="Customer ID.1")
print(merge_table)

    Call number Customer ID  Duration Representative Date of Call     Amount  \
0     Call_7271       C0003     116.0            R05   2023-01-01  128.00000
1     Call_7272       C0004       NaN            R05   2023-01-01  135.00000
2     Call_7273       C0005      68.0            R02   2023-01-01   96.76329
3     Call_7274       C0014     119.0            R02   2023-01-01   22.00000
4     Call_7275       C0011     128.0            R01   2023-01-02   31.00000
..          ...         ...       ...            ...          ...        ...
995   Call_8266       C0002      81.0            R05   2023-12-30   28.00000
996   Call_8267       C0007     127.0            R04   2023-12-30  215.00000
997   Call_8268       C0013     146.0            R05   2023-12-31  115.00000
998   Call_8269       C0010     123.0            R05   2023-12-31   64.00000
999   Call_8270       C0009     114.0            R01   2023-12-31   40.00000

     Rating Customer ID.1  Gedner  Age        City
0       4.9         C0003    Male   26  Cincinnati
1       2.9         C0004    Male   36  Cincinnati
2       4.7         C0005    Male   37    Columbus
3       2.9         C0014  Female   38    Columbus
4       NaN         C0011  Female   30  Cincinnati
..      ...           ...     ...  ...         ...
995     3.9         C0002    Male   31   Cleveland
996     3.8         C0007  Female   22   Cleveland
997     2.3         C0013  Female   37   Cleveland
998     3.7         C0010  Female   30   Cleveland
999     3.9         C0009  Female   25    Columbus

[1000 rows x 11 columns]

In [141]:
print(calls.columns.tolist())
print(customers.columns.tolist())

['Call number', 'Customer ID', 'Duration', 'Representative', 'Date of Call', 'Amount', 'Rating']
['Customer ID.1', 'Gedner', 'Age', 'City']